In [1]:
import numpy as np

In [2]:
a=np.array([5,6,9])
a

array([5, 6, 9])

In [3]:
a[0]

5

In [5]:
a=np.array([[1,2],[3,4],[4,5]])
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [6]:
a.ndim

2

In [7]:
a=np.array([5,6,7])

In [8]:
a.ndim

1

In [9]:
a.itemsize

4

In [10]:
a.dtype

dtype('int32')

In [11]:
a=np.array([[1,2],[3,4],[4,5]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [4., 5.]])

In [13]:
a.dtype

dtype('float64')

In [14]:
a.shape

(3, 2)

In [15]:
a.size

6

In [16]:
a=np.array([[1,2],[3,4],[4,5]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [25]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
a=np.array([[1,2],[3,4],[4,5]])

In [27]:
a.shape

(3, 2)

In [28]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 4, 5]])

In [29]:
a.ravel()

array([1, 2, 3, 4, 4, 5])

In [30]:
a.ravel().ndim

1

In [31]:
a.ndim

2

In [32]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [34]:
a.min()

1

In [35]:
a.max()

5

In [36]:
a.mean()

3.1666666666666665

In [37]:
a.sum()

19

In [39]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [38]:
a.sum(axis=0)

array([ 8, 11])

In [40]:
a.sum(axis=1)

array([3, 7, 9])

In [41]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.        , 2.23606798]])

In [42]:
a=np.array([[1,2],[3,4],[4,5]])
b=np.array([[6,7],[7,8],[9,10]])

In [43]:
a+b

array([[ 7,  9],
       [10, 12],
       [13, 15]])

In [44]:
a*b

array([[ 6, 14],
       [21, 32],
       [36, 50]])

In [45]:
a/b

array([[0.16666667, 0.28571429],
       [0.42857143, 0.5       ],
       [0.44444444, 0.5       ]])

In [46]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)