# IS vs ==
# == : Compares the element
# IS : Refer to the same object

In [10]:
import numpy as np

lst1 = ["Krish","Krish1","Krish2"]
lst2 = ["Krish","Krish1","Krish2"]

In [11]:
lst1==lst2

True

In [ ]:
# lst1 and lst2 has 2 different memory locaions

In [12]:
lst1 is lst2

False

In [13]:
lst2 is lst1

False

In [14]:
lst2 = lst1

In [15]:
lst2 is  lst1

True

In [16]:
lst1 is lst2

True

In [ ]:
# == - Compares the elements
# IS - refering to the same object ?

In [3]:
a = "Krish"
b = "Krish"
a==b

True

In [18]:
a = 10
b = 10
a==b

True

In [19]:
a is b

True

In [20]:
a = 4324
b = 4324
a==b

True

In [21]:
a is b

False

In [22]:
a = "Krish"
b = "Krish"

In [23]:
a is b

True

In [24]:
a == b

True

# Shallow Copy AND Deep Copy

In [ ]:
# Shallow Copy - Same memory location

In [25]:
a = np.array([1,2,3,4])

In [26]:
b = a

In [27]:
b[0]

1

In [28]:
b[0]=6

In [31]:
a

array([6, 2, 3, 4])

In [30]:
a

array([6, 2, 3, 4])

In [ ]:
# Deep Copy - Different memory location

In [41]:
a = np.array([1,2,3,4])

In [42]:
b = a.copy()

In [43]:
a[0]=6

In [44]:
a

array([6, 2, 3, 4])

In [45]:
b

array([1, 2, 3, 4])

# np.array vs np.asarray

In [ ]:
## asarray converts lists into array with the kind of datatype you shall provide

In [ ]:
#np.asarry(a,dtype=None,order=None)

In [57]:
arr = np.asarray([4,5,6])
arr

array([4, 5, 6])

In [58]:
arr1 = np.asarray(arr)
arr1

array([4, 5, 6])

In [59]:
arr is arr1

True

In [60]:
arr1 = np.asarray(arr,dtype=float)
arr1

array([4., 5., 6.])

In [61]:
arr is arr1

False

# General operation

In [64]:
a = np.array([1,2,3,4])

In [65]:
type(a)

numpy.ndarray

In [66]:
a.dtype

dtype('int32')

In [67]:
type(a)

numpy.ndarray

In [68]:
a.ndim

1

In [69]:
a.size

4

In [70]:
a.shape

(4,)

# arange and linespace

In [71]:
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
a = np.arange(0,9,4)
a

array([0, 4, 8])

In [73]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [75]:
a = np.arange(0,10,2).reshape(5,1)
a

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [79]:
a = np.linspace(2.0,3.0,9)
a

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ])

# Matrix

In [80]:
np.zeros(4)

array([0., 0., 0., 0.])

In [81]:
np.ones(4)

array([1., 1., 1., 1.])

In [83]:
a = 5 + np.ones(5)
a

array([6., 6., 6., 6., 6.])

In [84]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
a=np.logspace(2.0,3.0,num=4,base=10)
a

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

# Diagonal Array

In [86]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
np.diag(a)

array([ 0,  5, 10, 15])

In [89]:
np.diag(a,k=2)

array([2, 7])

In [90]:
np.diag(a,k=-1)

array([ 4,  9, 14])

# Random Number Generation

In [ ]:
## Random 0 to 1
## Standard Normal Distribution

In [91]:
np.random.rand(3,4)

array([[0.23697704, 0.7459055 , 0.94300545, 0.04108637],
       [0.32373838, 0.85998342, 0.30424408, 0.31067416],
       [0.92460832, 0.13768566, 0.6973637 , 0.94288663]])

In [92]:
np.random.randint(1,100)

56

In [96]:
np.random.randint(1,100,10)

array([92, 88, 76, 18, 69, 46, 16, 27, 99, 20])

In [97]:
a = np.random.randint(1,100,10)
a

array([97, 37, 93, 97,  2, 93, 11, 27, 73, 94])

In [98]:
np.sort(a)

array([ 2, 11, 27, 37, 73, 93, 93, 94, 97, 97])

In [99]:
a.max()

97

In [106]:
b=a.reshape(5,2)
b

array([[97, 37],
       [93, 97],
       [ 2, 93],
       [11, 27],
       [73, 94]])

In [107]:
b.max(axis=1)

array([97, 97, 93, 27, 94])

In [108]:
b.max(axis=0)

array([97, 97])

# Universal Function

In [110]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[4 7 9]
 [4 6 3]
 [1 9 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 4 1]
 [8 2 7]
 [2 1 1]]


In [111]:
mat1*mat2

array([[12, 28,  9],
       [32, 12, 21],
       [ 2,  9,  5]])

In [112]:
mat1*2

array([[ 8, 14, 18],
       [ 8, 12,  6],
       [ 2, 18, 10]])

In [113]:
mat1**2

array([[16, 49, 81],
       [16, 36,  9],
       [ 1, 81, 25]], dtype=int32)

In [114]:
mat1+mat2

array([[ 7, 11, 10],
       [12,  8, 10],
       [ 3, 10,  6]])

In [115]:
mat1@mat2 # Matrix Multiplication

array([[86, 39, 62],
       [66, 31, 49],
       [85, 27, 69]])

# Broadcasting

In [ ]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [116]:
a = np.zeros((4,4))
a= a+100
a

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [118]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [119]:
y = a + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [120]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [121]:
# add to each column of 'start' using broadcasting
y = a + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [122]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(add_scalar)

[100]


In [123]:
a+y

array([[200., 200., 200., 200.],
       [201., 201., 201., 201.],
       [202., 202., 202., 202.],
       [203., 203., 203., 203.]])

# Array Math

In [124]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 3 8]
 [1 2 8]
 [7 5 8]]

2nd Matrix of random single-digit numbers
------------
 [[7 5 6]
 [7 7 6]
 [1 5 6]]


In [125]:
np.sqrt(mat1)

array([[3.        , 1.73205081, 2.82842712],
       [1.        , 1.41421356, 2.82842712],
       [2.64575131, 2.23606798, 2.82842712]])

In [126]:
np.exp(a)

array([[2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43],
       [2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43],
       [2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43],
       [2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43]])

# Subseting

In [129]:
a = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",a)
a>50

Matrix of random 2-digit numbers
--------------------------------
 [[54 29 36 70 82]
 [73 70 89 23 53]
 [60 57 60 66 59]]


array([[ True, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [130]:
a[a>50]

array([54, 70, 82, 73, 70, 89, 53, 60, 57, 60, 66, 59])

# numpy.fromfunction

In [133]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [134]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])